### ISSUE TITLE
rubocopを導入する

### ISSUE THREAD

**Issue by og3** [og3/to-ban-hyo#13]
拡張することが明らかなので、保守のためにも書き方には注意する必要があるため

**Comment by og3** [comment]
### 導入
```
gem 'rubocop', require: false
```
require: falseってなに？

### 設定
.rubocop.yml
```
AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - vendor/**/*
  # Rails向けのRails copsを実行。"rubocop -R"と同じ
  RunRailsCops: true

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false
```

実行時にエラー
```
Error: obsolete parameter RunRailsCops (for AllCops) found in .rubocop.yml
Use the following configuration instead:
Rails:
  Enabled: true
```
下記を参考にrailsモードで実行する
https://qiita.com/necojackarc/items/8bc16092bbc69f17a16d

エラーは解決した。

### 実行
結果
```
37 files inspected, 63 offenses detected
```
うん、ちょっとずつ直していこう。。。

### 参考
http://blog-ja.sideci.com/entry/2015/03/12/160441
こういうのもいいかも。。
http://www.ohmyenter.com/rubocop-with-pre-commit/
